name = "SNEM2000d"
uuid = "67b735c3-0ed3-4096-85bf-0694979f3a45"
authors = ["tom philpott <tsp266@uowmail.edu.au> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
